language: php
branches:
  only:
  - master
  - "/^.*[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"
php:
- '7.2'
script: phpunit --bootstrap src/stub.php --test-suffix '-test.php,Test.php,.phpt'
  tests
notifications:
  email: false
before_deploy:
- composer phar:install-tools
- composer install --prefer-dist --no-dev --no-interaction
- php box.phar build
deploy:
  provider: releases
  api_key:
    secure: T/L3TPDyHLyOprZeywlI+DW2PAyfEZQSzFQhIF82Iyvn74nEHkkIV2rVnAWo0Z2QL0uFITUAOzd4FoBbsD9SFsUGeE6zgVsCg6EMuz4Q1nXzn5XwAww7NWDCe5cRaDvfXsBoscxt4w1pzSLydOjUEfu4rJO5+FZqr1ldKhD/WRSD+b+b3TmxznYDrocYJt4aZK30xtvr1Fh41OgO6Yw4JbxbuAbeirsZPxS5vs2BmJD6uIqdyvnpb1TixkpqCijSmuJewh+ErBAGDqjBqvPETRSHw5lHPpX9ejTEjn8WRkz62VP2fgZrmDS1hscThXpleLACCz0ayHTr/TH9hjxA7vF3zjnHYOnZxFbTBO500UJI13gpiTpk58Yl5tKaUon0dKMf35xBrJFdIrX2xMM+1sGKHcb9wYlkDbCnSUA7a3qhB/JjHvbYDVDQ2569m0H3j2/BYniFcrjk+lIG0vNe5VnP81EPYG9NsuO23k2Rz46DPqc9040HWtPuYQDu/Nrf+7PXVL07A5Q1TLZkbgyKBE8PorV3z8TBVPNOKaQOc2gNHSOORvS0VSTrst6Ppd6PWM3xm8hMPa0se3TYJ4VIjttvLRIKBnnGWlhV50Av8IOw4Zzn9s2elUy3MdXCisd/QNTaRY0rIw2ljwyEn2nRBWYaMfX3hf7zyUe4SQDMfNM=
  skip-cleanup: true
  file: test-phar-4.phar
  on:
    repo: bhoogter/test-phar-4
    tags: true
